# Generated by Django 5.1.4 on 2024-12-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.CharField(max_length=20, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Распространитель продукции')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='online_store.contacts', verbose_name='Контакты')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_to', to='online_store.dealer', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Объект сети',
                'verbose_name_plural': 'Объекты сети',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='dealer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='online_store.dealer', verbose_name='Дилер'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('date_of_release', models.DateField(verbose_name='Дата выхода продукта на рынок')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='online_store.dealer', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
